Repository FC-DEV3-Final-Project/KODAnect-frontend, pull requests merged in 2025-05, with the labels that each got.

#1 Feat: 스토리북 및 폴더 구조 세팅
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/features/.gitkeep
  src/index.css
  src/main.tsx
  src/pages/.gitkeep
  src/shared/api/.gitkeep
  src/shared/components/.gitkeep
  src/shared/hooks/.gitkeep
  src/shared/lib/.gitkeep
  src/shared/stores/.gitkeep
  src/shared/styles/index.css
  src/shared/types/.gitkeep
  src/shared/utils/.gitkeep
  src/stories/Button.stories.ts
  src/widget/.gitkeep
  tailwind.config.js
Labels: ⚙ Setting

#2 Feat: tailwind theme 설정
  package-lock.json
  plugins/krds-theme.js
  src/App.tsx
  tailwind.config.js
Labels: 🎨 Html & css

#16 Feat: button 컴포넌트 추가
  src/shared/components/Button.tsx
  src/shared/types/Button.types.ts
  src/stories/Button.stories.ts
Labels: ✨ Feature

#20 Feat : checkbox 컴포넌트 생성
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icon/check.svg
  src/shared/components/Checkbox.tsx
  src/shared/types/svg.d.ts
  src/stories/Checkbox.stories.tsx
  vite.config.ts
Labels: ✨ Feature

#22 Feat: 라우터 설정
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/Empty.tsx
  src/pages/Home.tsx
  src/pages/announcement/Notices.tsx
  src/pages/organ/info/BrainDeath.tsx
  src/pages/organ/info/OrganDonation.tsx
  src/pages/participation/Comparison.tsx
  src/pages/participation/Donors.tsx
  src/pages/participation/YearlyTrend.tsx
  src/pages/remembrance/Letters.tsx
  src/pages/remembrance/Members.tsx
  src/pages/remembrance/Recipients.tsx
  src/pages/remembrance/Stories.tsx
  src/pages/router.tsx
  src/shared/constant/sitemenu.ts
  src/widget/layout/Layout.tsx
  src/widget/layout/SideMenuLayout.tsx
Labels: ✨ Feature, ⚙ Setting
