Repository FC-DEV3-Final-Project/KODAnect-frontend, pull requests merged in 2025-06, with the labels that each got.

#5 Feat: Footer 컴포넌트 추가
  src/shared/constant/footerlink.ts
  src/stories/Footer.stories.ts
  src/widget/Footer.tsx
Labels: ✨ Feature

#8 Feat: SideMenu 컴포넌트 추가
  src/assets/images/announcement.png
  src/assets/images/organ.png
  src/assets/images/participation.png
  src/shared/constant/topvisual.ts
  src/shared/hooks/useCurrentTopMenuLabel.tsx
  src/widget/sideMenu/AccordionMenu.tsx
  src/widget/sideMenu/SideMenu.tsx
Labels: ✨ Feature

#17 Feat: dropdown 컴포넌트 생성
  src/shared/components/Dropdown.tsx
  src/stories/Dropdown.stories.ts
Labels: ✨ Feature

#30 Feat: pagination 컴포넌트 추가
  src/assets/icon/arrow-down.svg
  src/shared/components/Pagination.tsx
  src/stories/Pagination.stories.ts
Labels: ✨ Feature

#36 Style : 댓글 컴포넌트 퍼블리싱
  src/assets/icon/btn-more.svg
  src/assets/icon/reset.svg
  src/assets/icon/sound.svg
  src/shared/components/Label.tsx
  src/shared/components/TextInput.tsx
  src/shared/components/Textarea.tsx
  src/shared/components/comment/CommentArea.tsx
  src/shared/components/comment/CommentForm.tsx
  src/shared/components/comment/CommentItem.tsx
  src/shared/components/comment/CommentList.tsx
  src/stories/CommentArea.stories.tsx
  src/stories/TextArea.stories.ts
  src/stories/TextInput.stories.ts
Labels: 🎨 Html & css

#42 Feat: breadcrumb 링크 제거
  src/shared/components/Breadcrumb.tsx
Labels: ✨ Feature

#43 Feat : searchinput 컴포넌트 제작
  plugins/krds-theme.js
  src/assets/icon/search.svg
  src/shared/components/SearchInput.tsx
  src/stories/SearchInput.stories.tsx
Labels: ✨ Feature

#41 Feat: tab 컴포넌트 추가
  src/shared/components/Tab.tsx
  src/stories/Tab.stories.ts
Labels: ✨ Feature

#47 Feat: description 컴포넌트 추가
  src/shared/components/Description.tsx
  src/stories/Description.stories.ts
Labels: 🎨 Html & css

#60 Feat : 공통 컴포넌트 pagination 함수형 컴포넌트로 변경
  src/shared/components/Pagination.tsx
Labels: 🔨 Refactor

#34 Feat: LetterCard 컴포넌트 구현
  src/assets/icon/visibility.svg
  src/shared/components/LetterCrad.tsx
  src/shared/components/NewBadge.tsx
  src/stories/LetterCard.stories.ts
Labels: ✨ Feature, 🎨 Html & css

#64 Feat: Tab 수정 및 TopArea 추가
  src/shared/components/Tab.tsx
  src/shared/components/TopArea.tsx
  src/shared/components/TopVisual.tsx
  src/stories/Tab.stories.ts
Labels: ✨ Feature

#74 Feat: axios instance 설정
  package-lock.json
  package.json
  src/features/.gitkeep
  src/pages/.gitkeep
  src/shared/api/.gitkeep
  src/shared/api/axios/axiosInstance.ts
  src/shared/components/.gitkeep
  src/shared/hooks/.gitkeep
  src/shared/stores/.gitkeep
  src/shared/types/.gitkeep
  src/shared/utils/.gitkeep
  src/widget/.gitkeep
Labels: ⚙ Setting

#79 Feat: Captcha 컴포넌트 생성 및 스토리북 작성
  package-lock.json
  package.json
  src/shared/components/Captcha.tsx
  src/shared/utils/react-simple-captcha.d.ts
  src/stories/Captcha.stories.tsx
Labels: ✨ Feature

#82 Feat : 추모관 목록 조회 페이지 수정
  src/pages/Error.tsx
  src/pages/remembrance/Letters.tsx
  src/pages/remembrance/Members.tsx
  src/pages/remembrance/Recipients.tsx
  src/pages/remembrance/Stories.tsx
  src/pages/router.tsx
Labels: ✨ Feature

#80 Feat: 추모공간 작성 페이지
  package-lock.json
  package.json
  src/features/lettersForm/FormInfo.tsx
  src/features/lettersForm/PageTitle.tsx
  src/features/members/component/DonorCard.tsx
  src/features/members/component/TributeArea.tsx
  src/pages/Empty.tsx
  src/pages/Error.tsx
  src/pages/remembrance/Letters.tsx
  src/pages/remembrance/LettersForm.tsx
  src/pages/remembrance/Members.tsx
  src/pages/remembrance/Recipients.tsx
  src/pages/remembrance/RecipientsForm.tsx
  src/pages/remembrance/Stories.tsx
  src/pages/remembrance/StoriesForm.tsx
  src/pages/router.tsx
  src/shared/components/Breadcrumb.tsx
  src/shared/components/Button.tsx
  src/shared/components/Checkbox.tsx
  src/shared/components/Description.tsx
  src/shared/components/Dropdown.tsx
  src/shared/components/Label.tsx
  src/shared/components/Modal.tsx
  src/shared/components/Pagination.tsx
  src/shared/components/RadioButton.tsx
  src/shared/components/Tab.tsx
  src/shared/components/Table.tsx
  src/shared/components/TextInput.tsx
  src/shared/components/TopArea.tsx
  src/shared/components/calendar/Calendar.tsx
  src/shared/components/comment/CommentForm.tsx
  src/shared/components/comment/CommentList.tsx
  src/shared/styles/index.css
  src/shared/utils/ckeditor/CustomUploadAdapterPlugin.ts
  src/shared/utils/ckeditor/ImageUploadAdapter.ts
  src/stories/Button.stories.ts
  src/stories/Captcha.stories.tsx
  src/stories/Description.stories.ts
  src/stories/Pagination.stories.ts
  src/stories/RadioButton.stories.tsx
  src/widget/layout/SideMenuLayout.tsx
  tsconfig.json
Labels: ✨ Feature, 🎨 Html & css

#77 Feat : 추모관 상세 조회 페이지 구현
  package-lock.json
  package.json
  src/assets/images/memorialIcon/flower.svg
  src/assets/images/memorialIcon/hard.svg
  src/assets/images/memorialIcon/love.svg
  src/assets/images/memorialIcon/miss.svg
  src/assets/images/memorialIcon/proud.svg
  src/assets/images/memorialIcon/sad.svg
  src/assets/images/memorialIcon/see.svg
  src/features/letter-view/components/LetterContent.tsx
  src/features/letter-view/utils/getHeavenInfoItems.ts
  src/features/members-view/component/HeavenLetterList.tsx
  src/features/members-view/component/MemorialIconGroup.tsx
  src/features/members/component/TributeArea.tsx
  src/features/recipient-view/utils/getOrganName.ts
  src/features/recipient-view/utils/getRecipientInfoItems.ts
  src/features/story-view/utils/getAreaName.ts
  src/features/story-view/utils/getStoryInfoItems.ts
  src/pages/remembrance/LetterView.tsx
  src/pages/remembrance/MembersView.tsx
  src/pages/remembrance/RecipientView.tsx
  src/pages/remembrance/StoryView.tsx
  src/pages/router.tsx
  src/shared/api/common/types.ts
  src/shared/api/letter-view/comment/commentApi.ts
  src/shared/api/letter-view/letter/letterApi.ts
  src/shared/api/letter-view/letter/types.ts
  src/shared/api/members-view/comment/commentApi.ts
  src/shared/api/members-view/letter/letterApi.ts
  src/shared/api/members-view/letter/types.ts
  src/shared/api/members-view/member/memberApi.ts
  src/shared/api/members-view/member/types.ts
  src/shared/api/recipient-view/comment/commentApi.ts
  src/shared/api/recipient-view/comment/types.ts
  src/shared/api/recipient-view/letter/letterApi.ts
  src/shared/api/recipient-view/letter/types.ts
  src/shared/api/stories-view/comment/commentApi.ts
  src/shared/api/stories-view/story/storyApi.ts
  src/shared/api/stories-view/story/types.ts
  src/shared/components/Modal.tsx
  src/shared/components/TopVisual.tsx
  src/shared/components/comment/CommentArea.tsx
  src/shared/components/comment/CommentForm.tsx
  src/shared/components/comment/CommentItem.tsx
  src/shared/components/comment/CommentList.tsx
  src/shared/constant/letters-view.ts
  src/shared/constant/members-view.ts
  src/shared/constant/recipients-view.ts
  src/shared/constant/stories-view.ts
  src/shared/context/CommentContext.tsx
  src/shared/types/react-simple-captcha.d.ts
  src/shared/utils/withData.ts
  src/stories/CommentArea.stories.tsx
Labels: ✨ Feature, 🎨 Html & css

#83 Refactor: 추모관 상세 조회 router 파라미터 변경
  src/pages/remembrance/LetterView.tsx
  src/pages/remembrance/RecipientView.tsx
  src/pages/remembrance/StoryView.tsx
  src/pages/router.tsx
Labels: 🔨 Refactor

#87 Feat : 메인 하늘나라 편지 상세 페이지 이동 링크 수정
  src/features/home/component/letter/LetterCardList.tsx
Labels: 🔨 Refactor

#86 Refactor: 추모관 상세 조회 에러 처리
  src/pages/remembrance/LetterView.tsx
  src/pages/remembrance/MembersView.tsx
  src/pages/remembrance/RecipientView.tsx
  src/pages/remembrance/StoryView.tsx
Labels: 🔨 Refactor

#88 Feat: 추모공간 작성 페이지 수정
  src/pages/remembrance/LettersForm.tsx
  src/pages/remembrance/RecipientsForm.tsx
  src/pages/remembrance/StoriesForm.tsx
Labels: ✨ Feature

#90 Fix : 검색 클릭 시 cursor에 nextCursor 값 들어가는 문제 수정
  src/pages/remembrance/Members.tsx
Labels: ✨ Feature

#98 Docs : readme 최종본
  README.md
Labels: 📜 Docs
